import { ListResponse } from '@shared/types'

export type Product = {
  id: number
  sku: string

  name: string
  price: number
  priceInProductList: number
  defaultDisplayedPrice: number
  defaultDisplayedPriceFormatted: string

  unlimited: boolean
  inStock: boolean
  enabled: boolean

  url: string
  autogeneratedSlug: string
  customSlug: string

  imageUrl: string
  thumbnailUrl: string
  smallThumbnailUrl: string
  hdThumbnailUrl: string
  originalImageUrl: string
  originalImage: ProductImageMeta

  created: string
  updated: string
  createTimestamp: number
  updateTimestamp: number

  tax: ProductTax
  lowestPrice: number
  defaultDisplayedLowestPrice: number
  defaultDisplayedLowestPriceFormatted: string
  lowestPriceSettings: LowestPriceSettings

  isShippingRequired: boolean
  hasFreeShipping: boolean
  weight: number

  options: ProductOption[]

  shipping: ProductShipping

  borderInfo: ProductBorderInfo
  description: string

  galleryImages: ProductGalleryImage[]
  media: ProductMedia

  categoryIds: number[]
  categories: ProductCategory[]
  defaultCategoryId: number

  seoTitle: string
  seoDescription: string

  relatedProducts: RelatedProducts
  volume: number
  showOnFrontpage: number

  isSampleProduct: boolean
  googleItemCondition: string
  isGiftCard: boolean
  discountsAllowed: boolean
  nameYourPriceEnabled: boolean

  compositeComponents: any[]
  compositeParents: any[]
}

export type ProductCategory = {
  id: number
  enabled: boolean
  name: string
  nameTranslated: string
}

export type ProductOption = {
  type: string
  name: string
  nameTranslated: Record<string, string>
  choices: ProductOptionChoice[]
  defaultChoice: number
  required: boolean
}

export type ProductOptionChoice = {
  text: string
  textTranslated: Record<string, string>
  priceModifier: number
  priceModifierType: string
}

export type ProductTax = {
  taxable: boolean
  defaultLocationIncludedTaxRate: number
  enabledManualTaxes: any[]
  taxClassCode: string
}

export type LowestPriceSettings = {
  lowestPriceEnabled: boolean
}

export type ProductShipping = {
  type: string
  methodMarkup: number
  flatRate: number
  disabledMethods: any[]
  enabledMethods: any[]
}

export type ProductBorderInfo = {
  dominatingColor: RGBAColor
  homogeneity: boolean
}

export type RGBAColor = {
  red: number
  green: number
  blue: number
  alpha: number
}

export type ProductImageMeta = {
  url: string
  width: number
  height: number
}

export type ProductGalleryImage = {
  id: number
  url: string
  thumbnail: string
  originalImageUrl: string
  imageUrl: string
  hdThumbnailUrl: string
  thumbnailUrl: string
  smallThumbnailUrl: string
  width: number
  height: number
  orderBy: number
  borderInfo: ProductBorderInfo
}

export type ProductMedia = {
  images: ProductMediaImage[]
  videos: any[]
}

export type ProductMediaImage = {
  id: string
  isMain: boolean
  orderBy: number
  image160pxUrl: string
  image400pxUrl: string
  image800pxUrl: string
  image1500pxUrl: string
  imageOriginalUrl: string
}

export type RelatedProducts = {
  productIds: number[]
  relatedCategory: {
    enabled: boolean
    categoryId: number
    productCount: number
  }
}

export type ProductsResponse = ListResponse<Product>
